[versions]
godot-kotlin-jvm-replication = "0.0.1"
jvmToolchainVersion = "17"

kotlin="1.9.23"
godot-kotlin-jvm="0.8.2-4.2.1" # https://github.com/utopia-rise/godot-kotlin-jvm/releases
hippmann-godot-utilities="0.0.1"

kotlinx-coroutines-core="1.8.0" # https://github.com/Kotlin/kotlinx.coroutines/releases
kotlinx-serialization-json="1.6.3" # https://github.com/Kotlin/kotlinx.serialization/releases


[libraries]
hippmann-godot-utilities = { group = "ch.hippmann.godot", name = "utilities", version.ref = "hippmann-godot-utilities" }
godot-kotlin-jvm = { group = "com.utopia-rise", name = "godot-library-release", version.ref = "godot-kotlin-jvm" }

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

[plugins]
godot-kotlin-jvm = { id = "com.utopia-rise.godot-kotlin-jvm", version.ref = "godot-kotlin-jvm" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }