name: Create draft release

on:
  workflow_call:
    inputs:
      jvm-version:
        type: string

jobs:
  create-draft-release:
    name: Create GitHub draft release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ inputs.jvm-version }}

      - uses: gradle/actions/setup-gradle@v6

      - name: Generate changelog
        run: ./gradlew generateChangelog --no-daemon

      - name: Create draft release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
          body_path: build/changelog.md
